### ISSUE TITLE
سورس html

### ISSUE THREAD

**Issue by persin** [mortezakarimi/gentelella-rtl#1]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

#### برای سادگی و رواج زبان پارسی در صورت امکان موارد مورد ذکر خود را به صورت پارسی بنویسید.
با سلام ، در صورت امکان روش استفاده به صورت سورس html ساده را ارائه نمایید
</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">
سلام در صورت استفاده از مدیریت بسته ها مانند `bower` یا `npm` شما دسترسی به سورس `html` خالص دارید و می‌توانید در پروژه خود استفاده نمایید.

در صورت نیاز دانلود از طریق گیت هاب شما می‌توانید برنچ `gh-pages` را دانلود نمایید.
</div>

**Comment by persin** [comment]
ممنون از راهنمایتون
باید اطلاعاتم را در مورد گیت هاب بیشتر کنم
