### ISSUE TITLE
به هم ریختن داده ها

### ISSUE THREAD

**Issue by hanigamini** [mortezakarimi/gentelella-rtl#10]
<div dir="RTL">

با سلام.
وقتی از کد زیر استفاده کردم مرتب سازی داده های من که از back end می آید به هم میخوره

<div dir="ltr">

```
$('#datatable3').dataTable({
			"language": {
			"url": "/gentelella/Persian.json"
		},
		"pageLength": 100
		});
```
</div>
وقتی کد را کامنت میکنم و و آی دی datatable3 را از جدول حذف میکنم داده ها را درست نشون میده

</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">
بهتره قبل از ارسال مشکل مطالعه بیشتری در خصوص بسته‌های مورد استفادتون داشته باشید.

دو پیوند زیر را مشاهده نمایید تا اطلاعات مورد نیاز را در مورد روش کارکرد **datatable‍** بدست بیارید.

<div dir="ltr">

[Datatable Ajax](https://datatables.net/examples/data_sources/ajax.html)
[Datatable Filter Only](https://datatables.net/examples/basic_init/filter_only.html)
</div>
</div>

**Comment by hanigamini** [comment]
سلام.
قصدم فقط سوال بود
من از لینک ها چیزی متوجه نشدم
مگه میشه اولین بار که صفحه باز میشه داده ای که بهش میدیم را عوض کنه و به دلخواه خودش مرتب کنه؟

**Comment by mortezakarimi** [comment]
بله بر اساس داکیومنت موجود برای دیتاتیبل

**Comment by hanigamini** [comment]
سلام.
یعنی نمیشه داده های ما را به همون ترتیب نشون بده ؟
و سورت هم داشته باشه؟
