### ISSUE TITLE
laravel installing

### ISSUE THREAD

**Issue by DanteMason** [mortezakarimi/gentelella-rtl#12]
Hi
Thanks for doing such a great job
How can i install this on laravel and use it?
Thank you

**Comment by mortezakarimi** [comment]
Hi
You can download package using `bower` ,`npm`  or [github releases](https://github.com/mortezakarimi/gentelella-rtl/releases/latest) and use html in `public` folder
You can see [documentation](https://github.com/mortezakarimi/gentelella-rtl/tree/gh-pages/documentation)
see [gentelella on laravel](https://github.com/Labs64/laravel-boilerplate) package for inspiration
