### ISSUE TITLE
استفاده از فونت وزیر 19 به جای ایران سنس

### ISSUE THREAD

**Issue by MetaiR** [mortezakarimi/gentelella-rtl#13]
با توجه به لایسنس دار بودن فونت ایران سنس، به نظرم استفاده از فونت وزیر (نسخه ۱۹) میتونه جایگزین خوبی برای اون باشه که دوستانی ک مثل بنده مسائل این چنینی براشون مهمه هم بتونن از این قالب خوب استفاده کنن

**Comment by mortezakarimi** [comment]
ممنون از پیشنهاد شما
در استفاده از قالب شما می‌توانید فونت قالب را تغییر داده و از فونت دلخواه خود استفاده کنید
برای راحتی کار شما می‌توانید فایل‌های ‍`scss` را یک بار با استفاده از فوند مورد نظر خود کامپایل کنید و از پروژه استفاده نمایید.
در نسخه‌های بعدی قالب حتما از فونت مورد نظر شما استفاده خواهد شد.

**Comment by mortezakarimi** [comment]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

در نسخه نهایی از فونت وزیر و تغییر فونت پشتیبانی می‌شود 
https://github.com/mortezakarimi/gentelella-rtl/commit/ba4fb2d9a714c87bd51eabc9ec99865124c02386 مشاهده نمایید.
