### ISSUE TITLE
فارسی کردن اعداد

### ISSUE THREAD

**Issue by amirnejatbakhsh** [mortezakarimi/gentelella-rtl#14]
سلام دوست من. علی رقم توضیحاتی که در قسمت دانلود برای فارسی کردن اعداد نوشته بودی متوجه نشدم دقیقا باید چکار کنم تا اعداد فارسی بشه. ممنون میشم کمی بیشتر توضیح بدی

**Comment by amirnejatbakhsh** [comment]
با تغییر نام فونت از IRANSans به IRANSans_FaNum در خاصیت font-family استفاده شده در فایل custom.min.css اعداد فارسی شدند. منظورتون همین بود؟

**Comment by mortezakarimi** [comment]
<div dir="rtl">

سلام
شما می‌توانید با استفاده از فایل‌های `scss` موجود در پوشه پروژه که در پوشه `src\scss` وجود دارند تغییرات مورد نظر خود را در پروژه اعمال نمایید و سپس دوباره فایل‌ها را کامپایل نمایید.

برای تغییر فقط فونت به صورت ساده روشی که خودتان ارائه کردید درست می‌باشد.
> با تغییر نام فونت از IRANSans به IRANSans_FaNum در خاصیت font-family استفاده شده در فایل custom.min.css اعداد فارسی شدند. منظورتون همین بود؟

</div>
