### ISSUE TITLE
Fazalhaq

### ISSUE THREAD

**Issue by FazalhaqZaland** [mortezakarimi/gentelella-rtl#16]
سلام واحترامات جناب مرتضی کریمی 
ببخشین بسیار زیاد مه مکمل پروجیکت ره دانلود کردم وقت میبینم صفحات دیزاین خود را از دست داده مه هیچ نفامیدم چیقسم استفاده کنم ازش لطفا برم کمی راهنمای کنید چی کار کنم تا درست دیزاین اصلی ایش را بیگیرد چی چیز های ره باید اول انستال کنم چیقسم ازش استفاده کنم به کمک تان نیاز دارم

**Comment by mortezakarimi** [comment]
Please see this issue https://github.com/mortezakarimi/gentelella-rtl/issues/4
