### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by Kamalsroor** [mortezakarimi/gentelella-rtl#17]
[This package](https://www.jsdelivr.com/package/npm/gentelella-rtl) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by mortezakarimi** [comment]
Please feel free to pull request for adding changes

This list shows the main files list and other files can use from CDN files:

https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/js/custom.min.js
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/js/custom.min.js
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/js/helpers/smartresize.min.js
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/js/moment/moment.min.js
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/js/datepicker/daterangepicker.min.js

https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/css/custom.min.css
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/css/custom.min.css
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/css/daterangepicker.min.css
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/css/daterangepicker.min.css
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/css/maps/jquery-jvectormap-2.0.3.min.css

https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir.eot
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir.ttf
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir.woff
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir.woff2
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Black.eot
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Black.ttf
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Black.woff
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Black.woff2
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Bold.eot
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Bold.ttf
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Bold.woff
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Bold.woff2
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Light.eot
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Light.ttf
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Light.woff
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Light.woff2
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Medium.eot
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Medium.ttf
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Medium.woff
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Medium.woff2
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Thin.eot
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Thin.ttf
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Thin.woff
https://cdn.jsdelivr.net/npm/gentelella-rtl@1.4.0/build/fonts/Vazir/Vazir-Thin.woff2
