### ISSUE TITLE
استفاده از  چند جدول پویا در یک صفحه

### ISSUE THREAD

**Issue by maryamMOMENII** [mortezakarimi/gentelella-rtl#19]
<div dir="rtl">

سلام
وقت بخیر
ببخشید .
وقتی میخوام در یک صفحه تب دار چند جدول پویا باهم استفاده کنم
فقط یک جدول پویاست و بقیه حالت عادی دارند.
چطور میشه این مشکل رو حل کرد؟
</div>

**Comment by mortezakarimi** [comment]
You can use below link to find out how to use multiple data table in single page

[Multiple datatable in single page](https://www.datatables.net/examples/basic_init/multiple_tables.html)

**Comment by maryamMOMENII** [comment]
متشکر
