### ISSUE TITLE
مشکل فونت آوسام در فایرفاکس

### ISSUE THREAD

**Issue by mortezakarimi** [mortezakarimi/gentelella-rtl#2]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">
نمایش آیکون‌های فونت‌آوسام در مرورگر فایرفاکس در حالت لوکال فایل مشکل دارد.

نیاز به استفاده ازCDN وجود دارد.
</div>

**Comment by persin** [comment]
سلام ، جهت رفع اشکال فونت در فایرفاکس باید چی کار کرد؟

**Comment by mortezakarimi** [comment]
@persin سلام مشکل با استفاده از پروژه بر روی وب‌سرور حل می‌شود و فقط درحالت اجرا با استفاده از فایل‌ها وجود دارد.
