### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by alimo2** [mortezakarimi/gentelella-rtl#20]
Do you have bs4 in your roadmap?

**Comment by mortezakarimi** [comment]
I think based on project total contributors and stars it better to create another RTL template top of BS4 templates and don't wast our time to upgrade this template.
If more users request to upgrade this template maybe I have changed my mind, But for now, I think better convert one of below templates

https://github.com/puikinsh/sufee-admin-dashboard
https://github.com/puikinsh/CoolAdmin
https://github.com/puikinsh/concept
https://github.com/puikinsh/ElaAdmin

If you want to contribute feel free to contact me!

**Comment by alimo2** [comment]
Tnx
