### ISSUE TITLE
همگام سازی با فریم ورک ویو جی اس

### ISSUE THREAD

**Issue by pmsmasoud** [mortezakarimi/gentelella-rtl#22]
با سلام 
میخواستم بپرسم ایا این قالب با فریم ورک ویو جی اس همگام سازی داره ینی من میتونم اونو به ویو جی اس اضافه کنم ؟

**Comment by mortezakarimi** [comment]
<div dir="rtl">

سلام
متاسفانه نسخه Vue.js برای این قالب وجود نداره ولی شما میتونید با استفاده از نسخه HTML موجود ساختار Vue.js برای خودتون ایجاد کنید.
</div>
