### ISSUE TITLE
استفاده در ویو جی اس

### ISSUE THREAD

**Issue by pmsmasoud** [mortezakarimi/gentelella-rtl#23]
ببخشید من یه سوال پرسیدم شما متوجه منظور من نشدید 
الان این قالبی که درحال حاضر وجود داره و شما گذاشتید رو میشه من خودم به ویو جی اس اصافه کنم ؟ در  ادامه به مشکلی چیزی نمیخوره با ویو جی اس اگر نمیخوره تا من استفاده کنم ممنون میشم راهنمایی کنید با تشکر

**Comment by mortezakarimi** [comment]
<div dir="rtl">

واقعیتش من نمیدونم آیا درست میشه یا نه ولی بعید میدونم مشکلی پیش بیاد
ولی کاملا به خودتون بستگی داره که چطوری هماهنگ کنید ولی بعید میدونم مشکلی پیش بیاد
</div>

**Comment by pmsmasoud** [comment]
بعد یه سوال من این قالبو دانلود کردم از همینجا ولی بازش کردم بهم خورده بود ایا چیزی باید نصب کنم یا افزونه ی خاصی میخواد؟

**Comment by mortezakarimi** [comment]
بسیار عالی
