### ISSUE TITLE
فولدر  vendor  وجود ندارد

### ISSUE THREAD

**Issue by nesar2020** [mortezakarimi/gentelella-rtl#4]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

#### برای سادگی و رواج زبان پارسی در صورت امکان موارد مورد ذکر خود را به صورت پارسی بنویسید.

</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">
برای استفاده از کد برای production می‌توانید از بخش release در گیت‌هاب که در لینک زیر است دانلود نمایید که دارای فولدر vendors است.

[بخش رلیزهای گیت‌هاب](https://github.com/mortezakarimi/gentelella-rtl/releases)
در صورتی که برای توسعه پروژه نیاز به کدهای اصلی دارید می‌توان بعد از دانلود پروژه از گیت‌هاب با استفاده از `npm install` و سپس `bower install‍` تمام پکیج‌ها را دانلود نمایید و شروع به استفاده نمایید. که توضیحات کامل‌تر را در صفحه [readme.md](https://github.com/mortezakarimi/gentelella-rtl/blob/master/README.md) گیت‌هاب مشاهده نمایید.
</div>
