### ISSUE TITLE
English Numbers and Arabic T(ة)

### ISSUE THREAD

**Issue by almayahi** [mortezakarimi/gentelella-rtl#5]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

سلام 

1- اعداد رو چجوري به انگيلسي تغيير كرد؟ مثلا 123. 
2- حرف ة عربي به صورت همزه نوشته ميشه  اگه ميخوام همون ة نوشته بشه مثلا شركة 
عكس زير وقتي شركة رو مينوسيم به شركهْ نوشته ميشه 
![image](https://user-images.githubusercontent.com/15112440/40742883-86e8d0a0-6458-11e8-8fc6-a72f57f48499.png)

</div>

**Comment by mortezakarimi** [comment]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

سلام
مشکلاتی که شما ذکر کردید با تغییر فونت حل می شود ومشکل در فونت استفاده شده است که ظاهرا فونت `B Yekan` از حرف مورد نظر شما پشتیبانی نمی‌کند و همچنین اعداد را به صورت پیشفرض به اعداد فارسی تغییر می‌دهد. برای مثال شما می‌توانید فونت ‍‍`Tahoma` را در فایل `custom.min.css` جایگزین کنید.
</div>

**Comment by almayahi** [comment]
سلام 
من اين فونت رو داونلود كردم 
https://arbfonts.com/xm-yekan-font-download.html 
 و 
font-face 
را به اين فونت عوض كردم 

خيلي عاليه 
ممنون از شما
