### ISSUE TITLE
منوی چندسطحی در حالت مینیموم منو

### ISSUE THREAD

**Issue by amirsajjadi** [mortezakarimi/gentelella-rtl#6]
سلام. ممنون از شما بابت فارسی سازی این قالب
منوی چند سطحی در حالت مینیموم و کوچیک کار نمیکنه. البته من چک کردم توی قالب انگلیسی اون هم همین مشکل بود

**Comment by mortezakarimi** [comment]
<div dir="rtl">

با توجه به رفع ایراد شدن این مشکل در رپوزیتوری اصلی( [#693](https://github.com/puikinsh/gentelella/pull/693) ) مشکل حل گردید

</div>
