### ISSUE TITLE
چند جدول پویا در یک صفحه

### ISSUE THREAD

**Issue by hanigamini** [mortezakarimi/gentelella-rtl#7]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">
با سلام
برای قرار دادن 3 جدول پویای  پیش‌فرض  در یک صفحه باید چی کار کنم؟

اسم جدول سوم را به  `datatable3`  تغییر دادم و کد زیر را نوشتم ولی ولی متن های جستجو و ... را انگلیسی میاره

<div dir="ltr" align="left" style="direction:ltr;text-align:left;">

```
    $("#datatable3").DataTable();
```
</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">
با سلام ممنون از گزارش مشکل که ارائه کردید برای حل این مشکل می‌توانید از کد زیر استفاده نمایید.
<div dir="ltr">

```
$('#datatable3').dataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Persian.json"
        }
});
```
</div>
</div>

**Comment by hanigamini** [comment]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">
با سلام و تشکر
این جدول جستجو سمت راست افتاده و نمایش سمت چپ و اونی که اسمش datatable است جستجو سمت چپ و نمایش وسط افتاده
</div>
