### ISSUE TITLE
باگ جدول پویا

### ISSUE THREAD

**Issue by hanigamini** [mortezakarimi/gentelella-rtl#8]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

با سلام
در نسخه فارسی در جدول های پویا خط عمودی آخرین ستون نمایش داده نمیشه.
عکسش را در زیر میتونید ببینید.
خط عمودی قبل از حقوق نمایش داده نمیشه
در مرورگرهای مختلف هم همینطوره.
نسخه انگلیسی این مشکل را نداره
با تشکر
</div>

![capture](https://user-images.githubusercontent.com/12791970/44029061-3f364a82-9f11-11e8-8394-f6963ebf3503.JPG)

**Comment by mortezakarimi** [comment]
<div dir="rtl">

مشکل در آخرین نسخه رفع گردید.
</div>

**Comment by hanigamini** [comment]
با سلام.
با تشکر از زحمات شما.

**Comment by mortezakarimi** [comment]
<div dir="rtl">

شما می‌توانید با استفاده از روش‌های آپدیت پکیج منیجر مورد استفاده خودتون بسته را بروزنمایید یا با استفاده از لینک زیر آخرین ورژن را از گیت‌ها دانلود نمایید.
[دانلود آخرین نسخه](https://github.com/mortezakarimi/gentelella-rtl/releases/latest)
</div>

**Comment by hanigamini** [comment]
نمیخوام از روش آپدیت استفاده کنم و میخوام فایل ها را دستی توی فولدر تم بذارم
با نصب npm به کجا ها فایل اضافه میشه؟
فایل های زیر را جایگزین کردم و کلا خط های جدول ها رفت
آیا همه اینها نیازه؟
خطای زیر را هم در مرورگر میده

 build/css/custom.css
build/css/custom.css.map
build/css/custom.min.css
fonts\eot
fonts\ttf
fonts\woff
fonts\woff2

**Comment by hanigamini** [comment]
کلا خط های جدول ها رفت
