### ISSUE TITLE
خطای نبودن عکس sort_both.png

### ISSUE THREAD

**Issue by hanigamini** [mortezakarimi/gentelella-rtl#9]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">
با سلام.
این 2 عکس در فایل ها نیست و توی مرورگر خطا میده
</div>
<div dir="ltr">

`stylesheets/DataTables-1.10.13/images/sort_both.png`
`stylesheets/DataTables-1.10.13/images/sort_asc.png`
</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">

سلام در کدام فایل این خطا را مشاهده نمودید؟
<div>

**Comment by hanigamini** [comment]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">
در صفحاتی که جدول پویا داره و وقتی سورت میکنی این خطا در مرورگر میاد
</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">

بررسی که بنده انجام دادم چنین مشکلی وجود ندارد، احتمالا شما پروژه را به درستی نصب نکرده‌اید.
</div>

**Comment by hanigamini** [comment]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">

.sorting{background-image:url("DataTables-1.10.13/images/sort_both.png")}

در فایل

datatables.min.css

</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">

فایل اعلامی شما مربوط به پلاگین **datatable** و باز هم اعلام می‌‌کنم مشکل احتمالا از نحوه نصب شما میباشد.
</div>

**Comment by hanigamini** [comment]
<div dir="RTL" align="right" style="direction:rtl;text-align:right;">
بله درست میگید.
 من gentelella-rtl-1.3.-0 را کامل دانلود کردم و وقتی صفحه جدول پویا را باز میکنم خطای زیر را داره فقط

Failed to load file://cdn.datatables.net/plug-ins/1.10.19/i18n/Persian.json: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

</div>

**Comment by mortezakarimi** [comment]
<div dir="rtl">

علت این خطا اجرای مستقیم فایل‌های خام بدون استفاده از دامنه می‌باشد
که شما می‌توانید با اجرای آن در وب سرور‌های Apache ویا Nginx مشکل را حل نمایید و اطلاعات جداول پویا نیز ترجمه فارسی شوند.
</div>
